name: "Release dev container features"
on:
  workflow_dispatch:
  push:
    branches:
      - git-man_20241210

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/git-man_20241210' }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: "Publish"
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
